<?php
require_once __DIR__ . '/includes/functions.php';
$featured = db()->query("SELECT p.*, m.NomeMarca, c.NomeCategoria, (SELECT UrlImagem FROM tbl_ProdutoImagem pi WHERE pi.ID_Produto=p.ID_Produto ORDER BY Principal DESC, ID_Imagem ASC LIMIT 1) UrlImagem FROM tbl_Produtos p JOIN tbl_Marca m ON m.ID_Marca=p.ID_Marca JOIN tbl_Categoria c ON c.ID_Categoria=p.ID_Categoria WHERE p.StatusProduto IN ('Disponível','Esgotado') ORDER BY p.DataCadastro DESC LIMIT 4")->fetchAll();
$pageTitle='Tecnologia no seu nível'; require __DIR__ . '/includes/header.php'; ?>
<section class="hero"><div class="grid-bg"></div><div class="hero-copy"><div class="eyebrow">◈ tecnologia selecionada</div><h1>Domine a sua<br><span>próxima zona.</span></h1><p>Máquinas criadas para quem não aceita limite. Performance extrema, visual que impõe respeito e suporte de verdade.</p><p><a class="btn btn-primary" href="catalogo.php">Explorar computadores <b>→</b></a><a class="btn btn-outline" href="#destaques">Ver destaques</a></p></div><div class="hero-spec">RTX READY<br>FPS: SEM LIMITES<br>// BYTE ZONE 01</div><div class="hero-machine"></div></section>
<section class="benefits"><div class="benefit"><b>01</b><span>Produtos selecionados<br>para alta performance</span></div><div class="benefit"><b>02</b><span>Garantia e suporte<br>especializado</span></div><div class="benefit"><b>03</b><span>Pagamento em até<br>12x sem juros</span></div><div class="benefit"><b>04</b><span>Entrega segura<br>em todo Brasil</span></div></section>
<section class="section"><div class="section-head"><div><div class="eyebrow">Encontre sua máquina</div><h2>Escolha a sua zona.</h2></div><a class="link-arrow" href="catalogo.php">Ver todos os produtos →</a></div><div class="categories"><a class="category-card" href="catalogo.php?categoria=PC%20Gamer"><span class="number">01 / PC GAMER</span><h3>Jogue no<br>máximo.</h3><p>FPS insano, gráficos no ultra e setups que deixam marca.</p><span class="orb"></span></a><a class="category-card" href="catalogo.php?categoria=Desktop"><span class="number">02 / DESKTOP</span><h3>Trabalhe<br>gigante.</h3><p>Produtividade para quem transforma ideia em resultado.</p><span class="orb"></span></a><a class="category-card" href="catalogo.php?categoria=Notebook"><span class="number">03 / NOTEBOOK</span><h3>Leve a<br>potência.</h3><p>Mobilidade sem deixar desempenho para trás.</p><span class="orb"></span></a></div></section>
<section class="section" id="destaques"><div class="section-head"><div><div class="eyebrow">Seleção byte zone</div><h2>Em destaque agora.</h2></div><a class="link-arrow" href="catalogo.php">Ver catálogo →</a></div><?php if($featured): ?><div class="products"><?php foreach($featured as $p): ?><article class="product-card<?= is_product_unavailable($p) ? ' is-out' : '' ?>"><a href="produto.php?id=<?= $p['ID_Produto'] ?>"><span class="tag"><?= e($p['NomeCategoria']) ?></span><?php if (is_product_unavailable($p)): ?><span class="out-badge">ESGOTADO</span><?php endif; ?><div class="product-image"><img src="<?= e(product_image($p)) ?>" alt="<?= e($p['Nome_Prod']) ?>"></div><div class="product-info"><span class="product-brand"><?= e($p['NomeMarca']) ?></span><h3><?= e($p['Nome_Prod']) ?></h3><?php if($p['ValorPromocional']): ?><span class="old-price"><?= money((float)$p['Valor_Preco']) ?></span><?php endif; ?><b class="price"><?= money((float)($p['ValorPromocional'] ?: $p['Valor_Preco'])) ?></b><span class="stock"><?= is_product_unavailable($p) ? '● INDISPONÍVEL' : '● EM ESTOQUE' ?></span></div></a></article><?php endforeach; ?></div><?php else: ?><div class="empty"><h3>Sua vitrine está pronta para ganhar vida.</h3><p>Entre no painel administrativo e cadastre o primeiro computador da Byte Zone.</p><?php if(is_admin()): ?><a class="btn btn-primary" href="admin/produto_form.php">Adicionar produto</a><?php endif; ?></div><?php endif; ?></section>
<section class="cta-band"><div><div class="eyebrow">Precisa de ajuda?</div><h2>Não sabe qual máquina<br>combina com você?</h2></div><a class="btn" href="catalogo.php">Conhecer a linha completa →</a></section>
<?php require __DIR__ . '/includes/footer.php'; ?>
